version: "3.8"

services:
  cmake:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - cmake_build:/app/build  # Mount a volume for the build folder
    command: ["bash"]

volumes:
  cmake_build: 